# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('psc', ['energy', 'mobility', 'network', 'antenna', 'buildings', 'lte', 'point-to-point', 'sip'])
    module.source = [
        'model/psc-video-streaming.cc',
        'model/psc-video-streaming-distributions.cc',
        ]

    module_test = bld.create_ns3_module_test_library('psc')
    module_test.source = [
        ]

    headers = bld(features='ns3header')
    headers.module = 'psc'
    headers.source = [
        'model/psc-video-streaming.h',
        'model/psc-video-streaming-distributions.h',
        

        ]

    if (bld.env['ENABLE_EXAMPLES']):
        bld.recurse('examples')

    bld.ns3_python_bindings()

